### ISSUE TITLE
sample build fails

### ISSUE THREAD

**Issue by trouperk** [MartinKavik/seed-rs-realworld#2]
I was trying to build this site as a sample to get a feel for Seed with Rust. I used 'cargo make all' after cloning and cd'ing into the directory and it returned a build failure with the following information:

error[E0433]: failed to resolve: could not find `gloo_timers` in `seed`
 --> src/loading.rs:3:11
  |
3 | use seed::gloo_timers::future::TimeoutFuture;
  |           ^^^^^^^^^^^ could not find `gloo_timers` in `seed`

and 33 instances of the error below (the Clone portion)

error[E0277]: the trait bound `Ms: std::clone::Clone` is not satisfied
  --> src/entity/author.rs:33:1
   |
33 | / pub fn view<Ms>(username: &Username) -> Node<Ms> {
34 | |     a![
35 | |         class!["author"],
36 | |         attrs! {At::Href => Route::Profile(Cow::Borrowed(username)).to_string()},
37 | |         username.to_string()
38 | |     ]
39 | | }
   | |_^ the trait `std::clone::Clone` is not implemented for `Ms`
   |
   = help: consider adding a `where Ms: std::clone::Clone` bound
   = note: required by `seed::dom_types::Node`

I am using cargo version 1.39.0-nightly and cargo-make v0.22.2. The first error seems like it is coming from Seed. I would normally fix the second manually, but I have seen where resolving the first issue will solve many others (especially when they are all the same).

For what it is worth diagnostically, I have used Rust with Seed (your quickstart website and David OConnor's examples) without hitting any other these error messages.

Thanks for any insights you have and thanks for putting together some great fullstack Rust/Seed examples!

**Comment by MartinKavik** [comment]
It's because I needed Seed's master at the time of writing and your
cargo.lock is probably updated so it's not compatible anymore. I'll update
it in the morning / tomorrow and set fixed Seed version in cargo.toml.
Thanks for report.

**Comment by MartinKavik** [comment]
Changes in the latest commits:
- `Seed` set to `0.4.1` in `Cargo.toml`
- Fixed linter errors with the latest Rust and Clippy versions. 

> For what it is worth diagnostically, I have used Rust with Seed (your quickstart website and David OConnor's examples) without hitting any other these error messages.

I commit also `Cargo.lock` in my other projects because I'm not sure that everybody uses correct semantic versioning - it remembers compatible Seed version. This project has `Cargo.lock` in `.gitignore` - I'll remove it from `.gitignore` if we encounter similar issue again.

Please test it again and close issue if everything works and you don't have any other questions or suggestions. Thanks!

**Comment by trouperk** [comment]
I re-cloned and it worked with no issues. Thanks!
